### ISSUE TITLE
ModuleNotFoundError: No module named 'ragas.testset'; 'ragas' is not a package

### ISSUE THREAD

**Issue by Rugved2204** [explodinggradients/ragas#1080]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

Describe the bug
Just trying to import the package while pip show ragas correctly shows the package

Ragas version: 0.1.10
Python version: 3.10.12

Code to Reproduce
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

Error trace
Traceback (most recent call last):
  File "/home/ubuntu/scp-analyzer/rag-old/ragas.py", line 2, in <module>
    from ragas.testset.generator import TestsetGenerator
  File "/home/ubuntu/scp-analyzer/rag-old/ragas.py", line 2, in <module>
    from ragas.testset.generator import TestsetGenerator
ModuleNotFoundError: No module named 'ragas.testset'; 'ragas' is not a package

Additional context
I just installed the package (working in VSCode)

**Comment by Rugved2204** [comment]
Hello @dosu. I tried all the things mentioned by you. The issue still persists.

**Comment by Rugved2204** [comment]
@dosu Yes my script was named as ragas.py, The issue is now solved as I changed the name of the script. Thank you.
