### ISSUE TITLE
ValueError: a cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by Rugved2204** [explodinggradients/ragas#1087]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
ValueError: a cannot be empty unless no samples are taken

Ragas version: 0.1.10
Python version:3.10.12

**Code to Reproduce**
Share code to reproduce the issue
loader = PubMedLoader("liver", load_max_docs=10)
documents = loader.load()

# print(len(documents))
# print(documents)

embedding_model_name = 'BAAI/bge-small-en-v1.5'
embeddings = HuggingFaceEmbeddings(
      model_name=embedding_model_name,
      model_kwargs={'device':'cuda:0'}
   )

model_name = 'mistralai/Mistral-7B-Instruct-v0.2'

response_generation_llm = load_model(model_name, 0.1, 1024)

generator = TestsetGenerator.from_langchain(
    response_generation_llm,
    response_generation_llm,
    embeddings
)

# generate testset
testset = generator.generate_with_langchain_docs(documents, test_size=2, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})

**Error trace**
File "/home/ubuntu/scp-analyzer/rag-old/test_ragas.py", line 31, in <module>
    testset = generator.generate_with_langchain_docs(documents, test_size=2, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/testset/generator.py", line 210, in generate_with_langchain_docs
    return self.generate(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/testset/generator.py", line 279, in generate
    for n in self.docstore.get_random_nodes(k=test_size)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/testset/docstore.py", line 328, in get_random_nodes
    nodes = rng.choice(np.array(self.nodes), size=k, p=prob).tolist()
  File "numpy/random/_generator.pyx", line 803, in numpy.random._generator.Generator.choice
ValueError: a cannot be empty unless no samples are taken

**Expected behavior**
It should have generated the synthetic testset. Nodes are getting embedded but getting an error while generating

**Additional context**

**Comment by Rugved2204** [comment]
@dosu 
Traceback (most recent call last):
  File "/home/ubuntu/scp-analyzer/rag-old/test_ragas.py", line 31, in <module>
    testset = generator.generate_with_langchain_docs(documents, test_size=2, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/testset/generator.py", line 210, in generate_with_langchain_docs
    return self.generate(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/testset/generator.py", line 277, in generate
    available_nodes = self.docstore.get_random_nodes(k=test_size)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/testset/docstore.py", line 328, in get_random_nodes
    nodes = rng.choice(np.array(self.nodes), size=k, p=prob).tolist()
  File "numpy/random/_generator.pyx", line 803, in numpy.random._generator.Generator.choice
ValueError: a cannot be empty unless no samples are taken

The error still persists even after changing the code.

**Comment by Rugved2204** [comment]
@dosu yes the documents are not getting added to the docstore. Any Specific reason for that

**Comment by Rugved2204** [comment]
I am using my own LLM and embeddings from hugging face so can you help me to make it as a subclass of BaseRagasLLM and BaseRagasEmbeddings

**Comment by jjmachan** [comment]
@Rugved2204 were you able to solve this?
