### ISSUE TITLE
TypeError: object list can't be used in 'await' expression

### ISSUE THREAD

**Issue by Rugved2204** [explodinggradients/ragas#1097]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
TypeError: object list can't be used in 'await' expression

Ragas version:0.1.10
Python version:3.10.12

**Code to Reproduce**
from langchain_community.document_loaders import PubMedLoader
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context
from langchain_community.embeddings import HuggingFaceEmbeddings
from utils.models.loader import load_model
from datasets import load_dataset
from ragas.testset.extractor import KeyphraseExtractor
from langchain.text_splitter import TokenTextSplitter
from ragas.testset.docstore import InMemoryDocumentStore
from ragas.llms import BaseRagasLLM
from langchain_community.llms import HuggingFaceTextGenInference
import nest_asyncio
from langchain_huggingface import HuggingFaceEndpoint
import asyncio
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
import os

embedding_model_name = 'BAAI/bge-small-en-v1.5'
embeddings = HuggingFaceEmbeddings(
    model_name=embedding_model_name,
    model_kwargs={'device': 'cuda:0'}
)

model_name = 'mistralai/Mistral-7B-Instruct-v0.2'
llm_model = HuggingFaceEndpoint(
      endpoint_url="http://localhost:8000/",
      max_new_tokens=1024,
      temperature=0.1,
      huggingfacehub_api_token = "token",
  )

# # Load documents
loader = PubMedLoader("liver", load_max_docs=10)
documents = loader.load()
# print(f"Loaded {len(documents)} documents")

# Attempt to generate the testset
generator = TestsetGenerator.from_langchain(
    generator_llm=llm_model,
    critic_llm=llm_model,
    embeddings=embeddings,
)

testset = generator.generate_with_langchain_docs(documents, test_size=2, distributions={'simple': 0.5, 'reasoning': 0.25, 'multi_context': 0.25})
testset.to_pandas()

**Error trace**
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 87, in run
    results = self.loop.run_until_complete(self._aresults())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 79, in _aresults
    r = await future
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 37, in sema_coro
    return await coro
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 109, in wrapped_callable_async
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 104, in wrapped_callable_async
    result = await callable(*args, **kwargs)
TypeError: object list can't be used in 'await' expression

**Expected behavior**

**Additional context**

**Comment by Rugved2204** [comment]
Same issue still persists :
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 87, in run
    results = self.loop.run_until_complete(self._aresults())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 79, in _aresults
    r = await future
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 37, in sema_coro
    return await coro
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 109, in wrapped_callable_async
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 104, in wrapped_callable_async
    result = await callable(*args, **kwargs)
TypeError: object list can't be used in 'await' expression

**Comment by Rugved2204** [comment]
@dosu can you help me solve this problem

**Comment by Rugved2204** [comment]
@dosu

This is the new error I am getting now after making the changes 
Login successful
<coroutine object TestsetGenerator.generate_with_langchain_docs at 0x7a91422dbf40>
sys:1: RuntimeWarning: coroutine 'TestsetGenerator.generate_with_langchain_docs' was never awaited

**Comment by jjmachan** [comment]
@Rugved2204 were you able to solve this issue?
