### ISSUE TITLE
"ValueError: a cannot be empty unless no samples are taken" occurred when I used Local Ollama models

### ISSUE THREAD

**Issue by zhi-jiao** [explodinggradients/ragas#1265]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
"ValueError: a cannot be empty unless no samples are taken" 

Ragas version: 0.1.16
Python version: 3.11.9

**Code to Reproduce**
```
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context
from langchain_community.llms import Ollama
from langchain_community.document_loaders import DirectoryLoader

from langchain_community.embeddings import OllamaEmbeddings
embeddings = OllamaEmbeddings(model='nomic-embed-text')
loader = DirectoryLoader("./data")
documents = loader.load()

# generator with openai models
generator_llm = Ollama(model="gemma:2b")
critic_llm = Ollama(model="gemma:2b")
embeddings = OllamaEmbeddings(model='nomic-embed-text')


generator = TestsetGenerator.from_langchain(
    generator_llm,
    critic_llm,
    embeddings
)

# generate testset
testset = generator.generate_with_langchain_docs(documents, test_size=10, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
```
**Error trace**
```
Traceback (most recent call last):
  File "/home/zhsu20/Dunhuang_LLM/1.py", line 24, in <module>
    testset = generator.generate_with_langchain_docs(documents, test_size=10, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhsu20/miniconda3/envs/open-webui-env/lib/python3.11/site-packages/ragas/testset/generator.py", line 211, in generate_with_langchain_docs
    return self.generate(
           ^^^^^^^^^^^^^^
  File "/home/zhsu20/miniconda3/envs/open-webui-env/lib/python3.11/site-packages/ragas/_analytics.py", line 129, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhsu20/miniconda3/envs/open-webui-env/lib/python3.11/site-packages/ragas/testset/generator.py", line 281, in generate
    for n in self.docstore.get_random_nodes(k=test_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhsu20/miniconda3/envs/open-webui-env/lib/python3.11/site-packages/ragas/testset/docstore.py", line 328, in get_random_nodes
    nodes = self.run_config.rng.choice(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/_generator.pyx", line 803, in numpy.random._generator.Generator.choice
ValueError: a cannot be empty unless no samples are taken
```

**Additional context**
I have checked the data used in this code,  the node list is empty but the docs has been read.

**Comment by zhi-jiao** [comment]
I have added the code you implemented, here is the output:
```
Number of documents loaded: 1
Filename and doc_id are the same for all nodes.                                                                                                                                                       
[]
```
Now I'm sure that all the data have been loaded.

However, the bug occurred in the code below:

```
        current_nodes = [
            CurrentNodes(root_node=n, nodes=[n])
            for n in self.docstore.get_random_nodes(k=test_size)
        ]
```


I can't check wether there are enough nodes in  Docstore.
