### ISSUE TITLE
How to adapt language of result just exactly the same to the contexts given which is separated into several files and the files are in different languages.  

### ISSUE THREAD

**Issue by francescofan** [explodinggradients/ragas#1435]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
As the document of ragas says in "Automatic language adaptation"(https://docs.ragas.io/en/v0.1.1/howtos/applications/use_prompt_adaptation.html#language-adaptation-for-metrics)，we can adapt the language to the document using adapt Function. But I suppose that the document shows that I have to set the language in advance, because I have to know the language of the context I submit. But the actual situation is that I have some papers or documents in different language such as English, Japanese, Chinese, French. I would like to get a set of questions and ground-truth results which is written in the exactly the same language with the context I submit. Is that possible? If so, ,how to achieve it?

**Code Examples**
This community speaks code. Share your code snippets to help us understand your question better.

**Additional context**
Anything else you want to share with us?

**Comment by francescofan** [comment]
@dosu
can you list all the language parameter values could be set?

**Comment by francescofan** [comment]
@dosu
when I ran the code after modification of language, error occured as following:
**error**
Traceback (most recent call last):
  File "d:\Notes\2.Python\next_console\next_console_qa_evaluate\ragas\ragas_test.py", line 112, in <module>
    generator.adapt(language, evolutions=[simple, reasoning, conditional, multi_context])
  File "D:\anaconda3\envs\next_console_qa_evaluate\Lib\site-packages\ragas\testset\generator.py", line 340, in adapt
    self.docstore.extractor.adapt(language, cache_dir=cache_dir)
  File "D:\anaconda3\envs\next_console_qa_evaluate\Lib\site-packages\ragas\testset\extractor.py", line 61, in adapt
    self.extractor_prompt = self.extractor_prompt.adapt(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\next_console_qa_evaluate\Lib\site-packages\ragas\llms\prompt.py", line 185, in adapt
    self_cp = self._load(language, self.name, cache_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\next_console_qa_evaluate\Lib\site-packages\ragas\llms\prompt.py", line 286, in _load
    return cls(**json.load(open(path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\next_console_qa_evaluate\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Prompt
__root__
  output in example 1 is not in valid json format: Expecting value: line 1 column 1 (char 0) (type=value_error)

**code**
```python
generator = TestsetGenerator.from_langchain(
    generator_llm,
    critic_llm,
    embeddings
)

language = "zh"
generator.adapt(language, evolutions=[simple, reasoning, conditional, multi_context])
generator.save(evolutions=[simple, reasoning, multi_context,conditional])
```

**Comment by francescofan** [comment]
@dosu
based on the message above, where is the  output field?

**Comment by francescofan** [comment]
@dosu
I havn't define any example manually. Where could be the example located?

**Comment by francescofan** [comment]
@dosu could you tell the excat place or filename where i should check?

**Comment by francescofan** [comment]
@dosu in 'Lib\site-packages\ragas' anaconda packages directory,no file or directory is named as synthesizers.

**Comment by francescofan** [comment]
@dosu
I solved this problem while a new problem occured. 
In this funcition, generator.adapt(language, evolutions=[simple, reasoning, conditional, multi_context],cache_dir='xxxx')
if i don't set the value of cache_dir, the program may not find the correct directory. Because I am using the Windows system, but the default cache_dir is '/.cache\ragas' which is invalid in Windows.
But a new question came to me. After I run the following code:
```python
language = "zh"
generator.adapt(language, evolutions=[simple, reasoning, conditional, multi_context],cache_dir='.\\ragas\\cache\\')
generator.save(evolutions=[simple, reasoning, multi_context,conditional])
```
A directory 'zh' was created in '.\\ragas\\cache\\' and there are a lot of prompts stored as json files in directory 'zh'.
And accoding to the documents, there is no need to adapt the language again. I can run 'generator.generate_with_langchain_docs' function for many times. Is that so? How can I figure what language adaption I am using?

**Comment by francescofan** [comment]
@dosu
Do I need to set then cache_dir value as a GLOBAL parameter?
How can generator.generate_with_langchain_docs find which prompts it should use?

**Comment by francescofan** [comment]
@dosu
I mean how can generator.generate_with_langchain_docs always use the specific cache_dir prompts.
for example, I have '.\ragas\cache\zh' directory in which a lot of prompts JSON file are created. How can I generate_with_langchain_docs with these prompts JSON file always?

**Comment by francescofan** [comment]
@dosu
I finished your step 1, and there is already a directory '.\\ragas\\cache\\zh' here.
As to step 2 generate_with_langchain_docs doesn't take a cache_dir parameter, so where can I find settings and is the setting effective for function 'generate_with_langchain_docs'?
As to step 3, I don't find the way to use a specific cache_dir when running function 'generate_with_langchain_docs'.
So do i need to run generator.adapt(language, evolutions=[simple, reasoning, conditional, multi_context],cache_dir='.\\ragas\\cache\\') every time when I need to run generate_with_langchain_docs.
And finnally another question occured. If I run adpat function second time with the same cache_dir, an error occured that '  output in example 1 is not in valid json format: Expecting value: line 1 column 1 (char 0) (type=value_error)'. I printed the three parameters needed for then function as following:
cache_dir:.\ragas\cache
language:zh
name:keyphrase_extraction
And in the cache_dir, there is already a directory name 'zh' which was created last time.
Why and how to solve this.

**Comment by francescofan** [comment]
@dosu
hey, the JSON files were created by generator.save(evolutions=[simple, reasoning, multi_context,conditional]), how could it be invaild,guy?
