### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by amin-kh96** [explodinggradients/ragas#1447]
i deifned this function to not use the LLM calls but it still give me this error:

Exception has occurred: AttributeError
'list' object has no attribute 'get_sample_type'
  File "C:\Users\Amin\OneDrive - unige.it\Documenti\projectss\ragas-prototype\src\rag_eva.py", line 222, in <module>
    evaluation_report = evaluate(ragas_data, metrics=metrics, embeddings=ragas_embeddings,llm=custom_llm)  # Pass your custom LLM here
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get_sample_type'

my code is this:

# Define the custom LLM class
class CustomRagasLLM(BaseRagasLLM):
    def __init__(self, api_key: str = None):
        """
        Initialize the custom LLM, optionally using an API key if necessary.
        """
        self.api_key = api_key

    def _call(self, prompt: str) -> str:
        """
        Process the prompt and return a result. This can be customized to
        use a local model or perform any required logic.
        """
        if not self.api_key:
            return f"Processed: {prompt} (without API key)"
        else:
            # Handle LLM response if using an API
            return f"Processed: {prompt} (with API key: {self.api_key})"
    
    def generate_text(
        self,
        prompt: PromptValue,
        n: int = 1,
        temperature: float = 1e-8,
        stop: t.Optional[t.List[str]] = None,
        callbacks: t.List = []
    ) -> LLMResult:
        # Synchronous generation logic
        text = self._call(prompt)
        return LLMResult(generations=[Generation(text=text)])
    
    async def agenerate_text(
        self,
        prompt: PromptValue,
        n: int = 1,
        temperature: float = 1e-8,
        stop: t.Optional[t.List[str]] = None,
        callbacks: t.List = []
    ) -> LLMResult:
        """
        Asynchronous method to generate text. This should allow for async processing.
        """
        # Simulate an asynchronous call, here we directly call the sync method for now
        text =await self._call(prompt)
        return LLMResult(generations=[Generation(text=text)])

**Comment by amin-kh96** [comment]
@dosu.
but this does not exist in the Ragas library: EvaluationDataset.
which version of ragas are you using?

**Comment by amin-kh96** [comment]
@dosu.
i face this error : AttributeError: 'list' object has no attribute 'rename_columns'
and my  code is this: 
# Assuming data_set is a list of dictionaries
ragas_data = [
    {
        "question": entry["text_vector_1"],  # Assuming this is a list of strings
        "answer": entry["text_vector_2"],  # Assuming this is a list of strings
        "contexts": entry["chunks"]  # Assuming this is a list of lists of strings
    }
    for entry in data_set
]

# Create the required structure for Dataset
formatted_data = {
    "question": [entry["question"] for entry in ragas_data],
    "contexts": [entry["contexts"] for entry in ragas_data],
    "answer": [entry["answer"] for entry in ragas_data]
}

the important thing is that I have a list of floats(computed embeddings).

**Comment by ToBeAss** [comment]
> @dosu. how to fix this error: Exception has occurred: AttributeError 'list' object has no attribute 'rename_columns' File "C:\Users\Amin\git\ragas-prototype\src\rag_eva.py", line 196, in evaluation_report = evaluate(ragas_data, metrics=metrics, embeddings=ragas_embeddings,llm=custom_llm) # Pass your custom LLM here ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'list' object has no attribute 'rename_columns'


I have a similar issue when using Pandas DataFrame.

Traceback (most recent call last):
  File "/Users/tobiasmolland/GitHub/Larry-Llama/scripts/ragas_generate_testset.py", line 49, in <module>
    result = evaluate(
             ^^^^^^^^^
  File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/ragas/_analytics.py", line 129, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/ragas/evaluation.py", line 161, in evaluate
    dataset = remap_column_names(dataset, column_map)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/ragas/validation.py", line 19, in remap_column_names
    return dataset.rename_columns(inverse_column_map)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'rename_columns'

Any solution to this yet?

**Comment by amin-kh96** [comment]
no, I changed the format multiple times but it still gives me the error. I will share this with you if I find any solution.

**Comment by amin-kh96** [comment]
@dosu. 
the  EvaluationDataset does not exist in my ragas library.

**Comment by amin-kh96** [comment]
@dosu.
this part of my code is related to my data set. take a look at it and tell me which part of it requires changes.
# Assuming data_set is a list of dictionaries
ragas_data = [
    {
        "question": entry["text_vector_1"],  # Assuming this is a list of strings
        "answer": entry["text_vector_2"],  # Assuming this is a list of strings
        "contexts": entry["chunks"]  # Assuming this is a list of lists of strings
    }
    for entry in data_set
]

# Create the required structure for Dataset
formatted_data = {
    "question": [entry["question"] for entry in ragas_data],
    "contexts": [entry["contexts"] for entry in ragas_data],
    "answer": [entry["answer"] for entry in ragas_data]
}

# Create a Dataset using the Hugging Face `datasets` library
ragas_dataset = Dataset.from_dict(formatted_data)

**Comment by amin-kh96** [comment]
@dosu.
i see this error:
Exception has occurred: ValueError
Dataset feature "question" should be of type string
  File "C:\Users\Amin\git\ragas-prototype\src\rag_eva.py", line 199, in <module>
    evaluation_report = evaluate(ragas_dataset, metrics=metrics, embeddings=ragas_embeddings,llm=custom_llm)  # Pass your custom LLM here
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Dataset feature "question" should be of type string


the fromat is like this:
formatted_data = {
    "question": [entry["question"] for entry in ragas_data],
   "contexts": [entry["contexts"] for entry in ragas_data],
    "answer": [entry["answer"] for entry in ragas_data]
}

# Create a Dataset using the Hugging Face `datasets` library
ragas_dataset = Dataset.from_dict(formatted_data)

**Comment by amin-kh96** [comment]
@dosu.
but i have floats not the str, i have the embeddings for question and answer and also the chunks

**Comment by amin-kh96** [comment]
@dosu
how to adapt or create a custom evaluation logic that directly supports embeddings.

**Comment by amin-kh96** [comment]
@dosu @jjmachan 
you don't understand my point.
I created a custom embedding class to use the custom evaluation function(that directly supports the embeddings). but when I run it I see the error "the question must be the string".
this is my code:

# Assuming data_set is a list of dictionaries
ragas_data = [
    {
        "question": entry["text_vector_1"],  # Assuming this is a list of strings
        "answer": entry["text_vector_2"],  # Assuming this is a list of strings
        "contexts": entry["chunks"]  # Assuming this is a list of lists of strings
    }
    for entry in data_set
]

# Create the required structure that  structures the data for the Hugging Face Dataset creation.
formatted_data = {
    "question": [entry["question"] for entry in ragas_data],
   "contexts": [entry["contexts"] for entry in ragas_data],
    "answer": [entry["answer"] for entry in ragas_data]
}


# Define the column_map to match custom columns to expected ones
column_map = {
    "question": "question",  # Match to the correct column
    "answer": "answer",      # Match to the correct column
    "contexts": "contexts"   # Match to the correct column
}

# Create a Dataset using the Hugging Face `datasets` library
ragas_dataset = Dataset.from_dict(formatted_data)

model_name = 'distilbert-base-uncased'

class CustomHuggingFaceRagasEmbeddings(BaseRagasEmbeddings):
    def __init__(self, model_name: str, custom_embeddings: list = None):
        """
        Initialize the Custom Hugging Face Ragas Embeddings with the specified model and custom embeddings.
        
        Parameters:
            model_name (str): The name of the Hugging Face model to use (e.g., 'distilbert-base-uncased').
            custom_embeddings (list): A list of pre-computed custom embeddings (optional).
        """
        model_name = 'distilbert-base-uncased'
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name)
        self.custom_embeddings = custom_embeddings  # Store the custom embeddings

    def embed_documents(self, texts: list) -> np.ndarray:
        """
        Generate embeddings for a list of documents.
        
        Parameters:
            texts (list): A list of documents to embed.

        Returns:
            np.ndarray: An array of embeddings for the documents.
        """
        if self.custom_embeddings is not None:
            # If custom embeddings are provided, return those instead
            return np.array(self.custom_embeddings)
        
        # Generate new embeddings using the model if no custom embeddings are available
        inputs = self.tokenizer(texts, return_tensors='pt', padding=True, truncation=True)

        with torch.no_grad():
            outputs = self.model(**inputs)

        # Use the pooled output or the CLS token as the embedding
        embeddings = outputs.last_hidden_state[:, 0, :]  # CLS token for sentence embedding
        return embeddings.numpy()  # Convert to NumPy array

    def embed_query(self, query: str) -> np.ndarray:
        """
        Generate an embedding for a single query.
        
        Parameters:
            query (str): The query to embed.

        Returns:
            np.ndarray: The embedding for the query.
        """
        # If custom embeddings are provided, generate embedding based on those
        if self.custom_embeddings is not None:
            # You might want to handle how to relate the query to your custom embeddings
            raise NotImplementedError("Custom query embeddings are not supported with provided custom embeddings.")
        
        # Generate a new embedding using the model
        inputs = self.tokenizer(query, return_tensors='pt', padding=True, truncation=True)

        with torch.no_grad():
            outputs = self.model(**inputs)

        # Use the pooled output or the CLS token as the embedding
        embedding = outputs.last_hidden_state[:, 0, :]  # CLS token for single query embedding
        return embedding.numpy()  # Convert to NumPy array
    
# Initialize the custom embeddings class
custom_embeddings = CustomHuggingFaceRagasEmbeddings(ragas_dataset)


ragas_embeddings = CustomHuggingFaceRagasEmbeddings(model_name=model_name, custom_embeddings=custom_embeddings)

# Define the custom LLM class
class CustomRagasLLM(BaseRagasLLM):
    def __init__(self, api_key: str = None):
        """
        Initialize the custom LLM, optionally using an API key if necessary.
        """
        self.api_key = api_key

    def _call(self, prompt: str) -> str:
        """
        Process the prompt and return a result. This can be customized to
        use a local model or perform any required logic.
        """
        if not self.api_key:
            return f"Processed: {prompt} (without API key)"
        else:
            # Handle LLM response if using an API
            return f"Processed: {prompt} (with API key: {self.api_key})"
       
    def generate_text(
        self,
        prompt: PromptValue,
        n: int = 1,
        temperature: float = 1e-8,
        stop: t.Optional[t.List[str]] = None,
        callbacks: t.List = []
    ) -> LLMResult:
        # Synchronous generation logic
        text = self._call(prompt)
        return LLMResult(generations=[Generation(text=text)])
    async def agenerate_text(
        self,
        prompt: PromptValue,
        n: int = 1,
        temperature: float = 1e-8,
        stop: t.Optional[t.List[str]] = None,
        callbacks: t.List = []
    ) -> LLMResult:
        """
        Asynchronous method to generate text. This should allow for async processing.
        """
        # Simulate an asynchronous call, here we directly call the sync method for now
        text =await self._call(prompt)
        return LLMResult(generations=[Generation(text=text)])     
    
    
custom_llm =CustomRagasLLM(api_key=None) 

# Define the evaluation metrics
metrics = [context_utilization]
# Create a Dataset using the Hugging Face `datasets` library
#ragas_dataset = Dataset.from_dict(formatted_data)
# Run the evaluation
evaluation_report = evaluate(ragas_dataset, metrics=metrics, embeddings=ragas_embeddings,llm=custom_llm, column_map=column_map)  # Pass your custom LLM here

print("RAGAS Evaluation Report:")
print(evaluation_report)

**Comment by amin-kh96** [comment]
> ```python
> from ragas import EvaluationDataset
> ```

no my dataset is not a list or str, pandas is not

> > @dosu. how to fix this error: Exception has occurred: AttributeError 'list' object has no attribute 'rename_columns' File "C:\Users\Amin\git\ragas-prototype\src\rag_eva.py", line 196, in evaluation_report = evaluate(ragas_data, metrics=metrics, embeddings=ragas_embeddings,llm=custom_llm) # Pass your custom LLM here ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'list' object has no attribute 'rename_columns'
> 
> I have a similar issue when using Pandas DataFrame.
> 
> ### Error:
> Traceback (most recent call last): File "/Users/tobiasmolland/GitHub/Larry-Llama/scripts/ragas_generate_testset.py", line 49, in result = evaluate( ^^^^^^^^^ File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/ragas/_analytics.py", line 129, in wrapper result = func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/ragas/evaluation.py", line 161, in evaluate dataset = remap_column_names(dataset, column_map) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/ragas/validation.py", line 19, in remap_column_names return dataset.rename_columns(inverse_column_map) ^^^^^^^^^^^^^^^^^^^^^^ File "/Users/tobiasmolland/GitHub/Larry-Llama/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in **getattr** return object.**getattribute**(self, name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'DataFrame' object has no attribute 'rename_columns'
> 
> ### Code used:
> ```python
> # import dependencies
> from ragas.testset.generator import TestsetGenerator
> from ragas.testset.evolutions import simple, reasoning, multi_context
> from langchain_openai import ChatOpenAI, OpenAIEmbeddings
> 
> # set models
> generator_llm = ChatOpenAI(model="gpt-3.5-turbo-16k")
> critic_llm = ChatOpenAI(model="gpt-4")
> embeddings = OpenAIEmbeddings()
> 
> # create generator with models
> generator = TestsetGenerator.from_langchain(
>     generator_llm,
>     critic_llm,
>     embeddings
> )
> 
> # generate testset
> testset = generator.generate_with_langchain_docs(documents, test_size=5, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
> df = testset.to_pandas()
> 
> # evaluate testset
> from ragas.metrics import (
>     answer_relevancy,
>     faithfulness,
>     context_recall,
>     context_precision,
> )
> 
> from ragas import evaluate
> 
> result = evaluate(
>     df,
>     metrics=[
>         context_precision,
>         faithfulness,
>         answer_relevancy,
>         context_recall,
>     ],
> )
> result
> ```
> 
> Any solution to this yet?

use colum_map method,

**Comment by rcruzgar** [comment]
Hi! Something similar happens to my evaluation dataset, which is a dataframe with columns: ['user_input', 'reference_contexts', 'reference', 'synthesizer_name'], created with **generator.generate_with_langchain_docs**. The error is: 

`AttributeError: 'DataFrame' object has no attribute 'get_sample_type'`.

My code:

```
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness, SemanticSimilarity
from ragas import evaluate

generator_embeddings =  LangchainEmbeddingsWrapper(embedder)
generator_llm = LangchainLLMWrapper(llm)

metrics = [
    LLMContextRecall(llm=generator_llm), 
    FactualCorrectness(llm=generator_llm), 
    Faithfulness(llm=generator_llm),
    SemanticSimilarity(embeddings=generator_embeddings)
]
results = evaluate(dataset=df_test, metrics=metrics)
```
