### ISSUE TITLE
Bug with context precision evaluator `LLMContextPrecisionWithoutReference`

### ISSUE THREAD

**Issue by ShihuiZhu** [explodinggradients/ragas#1594]
[x] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
The LLM-based context precision without reference class (`LLMContextPrecisionWithoutReference`) still try to access the reference answer in the SingleTurnSample instance.

```
File "/Users/miniconda3/envs/chatbot/lib/python3.11/site-packages/ragas/metrics/_context_precision.py", line 164, in _ascore
    answer=row["reference"],
```

Ragas version: 0.2.2
Python version: 3.11

**Code to Reproduce**
```
from ragas import SingleTurnSample
from ragas.metrics import LLMContextPrecisionWithoutReference

context_precision = LLMContextPrecisionWithoutReference()

sample = SingleTurnSample(
    user_input="Where is the Eiffel Tower located?",
    response="The Eiffel Tower is located in Paris.",
    retrieved_contexts=["The Eiffel Tower is located in Paris."], 
)

context_precision.single_turn_score(sample)
```

**Error trace**
```
Traceback (most recent call last):
  File "/Users/langchain-rag/test_ragas.py", line 38, in <module>
    context_precision.single_turn_score(sample)
  File "/Users/miniconda3/envs/chatbot/lib/python3.11/site-packages/ragas/metrics/base.py", line 258, in single_turn_score
    raise e
  File "/Users/miniconda3/envs/chatbot/lib/python3.11/site-packages/ragas/metrics/base.py", line 252, in single_turn_score
    score = loop.run_until_complete(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miniconda3/envs/chatbot/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/miniconda3/envs/chatbot/lib/python3.11/site-packages/ragas/metrics/_context_precision.py", line 147, in _single_turn_ascore
    return await self._ascore(row, callbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miniconda3/envs/chatbot/lib/python3.11/site-packages/ragas/metrics/_context_precision.py", line 164, in _ascore
    answer=row["reference"],
           ~~~^^^^^^^^^^^^^
KeyError: 'reference'
```

**Expected behavior**
Output should be a context precision score

**Comment by jjmachan** [comment]
this has been fixed with #1567 so closing this now
do try out the latest version v0.2.3 and see if you get it working 🙂
