### ISSUE TITLE
Version file not found

### ISSUE THREAD

**Issue by ejoly3** [explodinggradients/ragas#1761]
[X] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

I have installed ragas from git and added the path the PYTHONPATH
Trying to generate a test set using the code at: https://docs.ragas.io/en/v0.1.21/howtos/integrations/llamaindex.html
I get the error
ModuleNotFoundError: No module named 'ragas._version'

Ragas version: 0.2.8
Python version: 3.12

**Code**
from ragas.testset.synthesizers.generate import TestsetGenerator

**Error Trace** - file path to git repo shortened to PATH for privacy
Traceback (most recent call last):
  File "PATH\myScript.py", line 5, in <module>
    from ragas.testset.synthesizers.generate import TestsetGenerator
  File "PATH\src\ragas\__init__.py", line 1, in <module>
    from ragas.dataset_schema import EvaluationDataset, MultiTurnSample, SingleTurnSample
  File "PATH\src\ragas\dataset_schema.py", line 19, in <module>
    from ragas.sdk import RAGAS_API_URL, RAGAS_APP_URL, upload_packet
  File PATH\src\ragas\sdk.py", line 10, in <module>
    from ragas._version import __version__
ModuleNotFoundError: No module named 'ragas._version'

**Expected behavior**
Import modules

**Additional context**
I have a feeling this is a problem with how I installed ragas and not a bug with the module, but given that I haven't found any issues documenting this hopefully the answer can help others that make the same mistake.

**Comment by sahusiddharth** [comment]
Hi @ejoly3,

Have you tried reinstalling the ragas module?

```
pip install --upgrade ragas
```

If the issue persists, you can try running these commands, which helped resolve it for me:

```
pip install -U setuptools
pip install -e ".[dev]"
```

Let me know how it goes for you.
