### ISSUE TITLE
`NameError: name 'PromptValue' is not defined` when running synthetic data generation example

### ISSUE THREAD

**Issue by dbolotov** [explodinggradients/ragas#426]
**Describe the bug**
When running the synthetic data generation example from https://docs.ragas.io/en/latest/getstarted/testset_generation.html#get-started-testset-generation, I get the error:

 `NameError: name 'PromptValue' is not defined` 

on the line:

 `testset = testsetgenerator.generate(documents, test_size=test_size)`.

Ragas version: `0.0.23.dev25+gbad3a8e`
Python version: `3.11`

**Code to Reproduce**

```
import os
os.environ["OPENAI_API_KEY"] = "KEY GOES HERE"


from llama_index import download_loader

SemanticScholarReader = download_loader("SemanticScholarReader")
loader = SemanticScholarReader()
# Narrow down the search space
query_space = "large language models"
# Increase the limit to obtain more documents
documents = loader.load_data(query=query_space, limit=10)


from ragas.testset import TestsetGenerator

testsetgenerator = TestsetGenerator.from_default()
test_size = 10
testset = testsetgenerator.generate(documents, test_size=test_size)
```

**Error trace**

```
testset = testsetgenerator.generate(documents, test_size=test_size)
C:\Users\DMBO\AppData\Local\Anaconda3\envs\docgpt_ragas_py311\Lib\site-packages\ragas\testset\testset_generator.py:402: UserWarning: Most documents are too short
  warnings.warn("Most documents are too short")
  0%|          | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 6, in <module>
  File "C:\Users\DMBO\AppData\Local\Anaconda3\envs\docgpt_ragas_py311\Lib\site-packages\ragas\testset\testset_generator.py", line 421, in generate
    raise e
  File "C:\Users\DMBO\AppData\Local\Anaconda3\envs\docgpt_ragas_py311\Lib\site-packages\ragas\testset\testset_generator.py", line 417, in generate
    proposal = self._make_proposal(curr_node, neighbor_nodes, evolve_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DMBO\AppData\Local\Anaconda3\envs\docgpt_ragas_py311\Lib\site-packages\ragas\testset\testset_generator.py", line 315, in _make_proposal
    score = self._filter_context(text_chunk)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DMBO\AppData\Local\Anaconda3\envs\docgpt_ragas_py311\Lib\site-packages\ragas\testset\testset_generator.py", line 201, in _filter_context
    results = self.critic_llm.generate_text_with_hmpt(prompts=[prompt])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DMBO\AppData\Local\Anaconda3\envs\docgpt_ragas_py311\Lib\site-packages\ragas\llms\base.py", line 69, in generate_text_with_hmpt
    prompt = PromptValue(prompt_str=prompts[0].format())
             ^^^^^^^^^^^
NameError: name 'PromptValue' is not defined
```

**Expected behavior**
I expected the test set to be generated without error.

**Comment by shahules786** [comment]
Hey, thanks for sharing this @dbolotov . I have raised a PR here https://github.com/explodinggradients/ragas/pull/427 to fix this. Will be merged soon.
