### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by CXLiang123** [explodinggradients/ragas#460]
**Describe the bug**
Traceback (most recent call last):
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas_tutor.py", line 69, in <module>
    eva()
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas_tutor.py", line 44, in eva
    result = evaluate(datasets,metrics=[#faithfulness,
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas/evaluation.py", line 102, in evaluate
    metric.score(dataset)
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas/metrics/base.py", line 76, in score
    score = self._score_batch(dataset.select(batch), callbacks=group)
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas/metrics/_answer_relevance.py", line 123, in _score_batch
    results = self.llm.generate(
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas/llms/openai.py", line 153, in generate
    llm_results = run_async_tasks(
  File "/root/autodl-tmp/cxl_workspace/com/basic_neural_networks_pytorch/chapter_llm/rag/ragas/async_utils.py", line 47, in run_async_tasks
    raise RuntimeError("Fatal error occurred while running async tasks.", e)
RuntimeError: ('Fatal error occurred while running async tasks.', APITimeoutError('Request timed out.'))

Ragas version:0.0.22
Python version:3.10

**Code to Reproduce**
def eva():
    datasets = Dataset.from_json(DATAS_JSON)

    answer_similarity.threshold = None #不使用阈值，可直接记录相似度
    answer_correctness.answer_similarity.threshold = None #同上

    my_aspect = AspectCritique(name="children", definition="Is the submission safe to children?") #自定义一个aspect

    result = evaluate(datasets,metrics=[#faithfulness,
                                        answer_relevancy,
                                        context_precision,
                                        context_recall,
                                        faithfulness,
                                        ])
    
    """
                                        answer_relevancy,
                                        answer_similarity,
                                        answer_correctness,
                                        context_relevancy,
                                        context_precision,
                                        context_recall,
                                        harmfulness,
                                        maliciousness,
                                        coherence,
                                        correctness,
                                        conciseness,
                                        my_aspect
    """
    # print(result)
    reports_manager.gen_report(result)

**Error trace**

**Expected behavior**

**Additional context**
Do I need to install a VPN tool on the server?

**Comment by owerbai** [comment]
the same problem ,with vpn
