### ISSUE TITLE
Metric language adapter AttributeError

### ISSUE THREAD

**Issue by Breno-de-Angelo** [explodinggradients/ragas#573]
I am running the metric adapter as described in the docs, but I am getting an error.

Ragas version: 0.1.0
Python version: 3.8.10

**Code to Reproduce**
```python
from ragas.metrics import (
    faithfulness,
    answer_correctness,
)
from langchain.chat_models import ChatOpenAI
from ragas import adapt

# llm used for adaptation
openai_model = ChatOpenAI(model_name="gpt-4")

adapt(metrics=[faithfulness,answer_correctness], language="hindi", llm=openai_model)
```

**Error trace**
Traceback (most recent call last):
  File "/home/breno/aumo/aumogpt-breno/teste.py", line 11, in <module>
    adapt(metrics=[faithfulness,answer_correctness], language="hindi", llm=openai_model)
  File "/home/breno/.local/lib/python3.8/site-packages/ragas/adaptation.py", line 36, in adapt
    metric.adapt(language, cache_dir=cache_dir)
  File "/home/breno/.local/lib/python3.8/site-packages/ragas/metrics/_faithfulness.py", line 207, in adapt
    self.nli_statements_message = self.nli_statements_message.adapt(
  File "/home/breno/.local/lib/python3.8/site-packages/ragas/llms/prompt.py", line 190, in adapt
    output_keys.append(get_all_keys(example.get(self.output_key)))
  File "/home/breno/.local/lib/python3.8/site-packages/ragas/llms/prompt.py", line 154, in get_all_keys
    for key, value in nested_json.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by shahules786** [comment]
Hey @Breno-de-Angelo , I'm on it. Will raise a fix soon.

**Comment by shahules786** [comment]
@Breno-de-Angelo I have raised a fix, please reinstall ragas from the source and try again once merged.

**Comment by Breno-de-Angelo** [comment]
Thank you @shahules786 !
