### ISSUE TITLE
Don't work prompt adapt NLI_STATEMENTS_MESSAGE (Adapted output keys do not match with the original output keys)

### ISSUE THREAD

**Issue by vadimbezborodow** [explodinggradients/ragas#639]
**Describe the bug**
You cannot adapt the *NLI_STATEMENTS_MESSAGE* prompt to another language, but *LONG_FORM_ANSWER_PROMPT* works

Ragas version: 0.1.1
Python version: 3.11.7

**Code to Reproduce**
```
from ragas.llms.prompt import Prompt
from langchain_openai.chat_models import ChatOpenAI
from ragas.llms.base import LangchainLLMWrapper

openai_model = LangchainLLMWrapper(ChatOpenAI(model="gpt-3.5-turbo"))

NLI_STATEMENTS_MESSAGE = Prompt(
    name="nli_statements",
    instruction="Natural language inference. Use only 'Yes' (1), 'No' (0) and 'Null' (-1) as verdict.",
    examples=[
        {
            "context": """John is a student at XYZ University. He is pursuing a degree in Computer Science. He is enrolled in several courses this semester, including Data Structures, Algorithms, and Database Management. John is a diligent student and spends a significant amount of time studying and completing assignments. He often stays late in the library to work on his projects.""",
            "statements": """
            statement_1: John is majoring in Biology.
            statement_2: John is taking a course on Artificial Intelligence.
            statement_3: John is a dedicated student.
            statement_4: John has a part-time job.
            """,
            "answer": [
                {
                    "statement_1": "John is majoring in Biology.",
                    "reason": "John's major is explicitly mentioned as Computer Science. There is no information suggesting he is majoring in Biology.",
                    "verdict": "0",
                },
                {
                    "statement_2": "John is taking a course on Artificial Intelligence.",
                    "reason": "The context mentions the courses John is currently enrolled in, and Artificial Intelligence is not mentioned. Therefore, it cannot be deduced that John is taking a course on AI.",
                    "verdict": "0",
                },
                {
                    "statement_3": "John is a dedicated student.",
                    "reason": "The context states that he spends a significant amount of time studying and completing assignments. Additionally, it mentions that he often stays late in the library to work on his projects, which implies dedication.",
                    "verdict": "1",
                },
                {
                    "statement_4": "John has a part-time job.",
                    "reason": "There is no information given in the context about John having a part-time job.",
                    "verdict": "0",
                },
            ],
        },
        {
            "context": """Photosynthesis is a process used by plants, algae, and certain bacteria to convert light energy into chemical energy.""",
            "statements": """statement_1: Albert Einstein was a genius.""",
            "answer": {
                "statement_1": "Albert Einstein was a genius.",
                "reason": "The context and statement are unrelated",
                "verdict": "0",
            },
        },
        {
            "context": """Albert Einstein was a German-born theoretical physicist who is widely held to be one of the greatest and most influential scientists of all time.""",
            "statements": """statement_1: Nil""",
            "answer": {
                "statement_1": "Nil",
                "reason": "The statement is invalid",
                "verdict": "-1",
            },
        },
    ],
    input_keys=["context", "statements"],
    output_key="answer",
    output_type="JSON",
)  # noqa: E501

adapted_prompt = NLI_STATEMENTS_MESSAGE.adapt(language="russian", llm=openai_model)
print(adapted_prompt.to_string())
```

**Error trace**

> Traceback (most recent call last):
>   File "/home/../.../main.py", line 105, in <module>
>     adapted_prompt = NLI_STATEMENTS_MESSAGE.adapt(language="spanish", llm=openai_model)
>   File "/home/.../.../.../lib/python3.10/site-packages/ragas/llms/prompt.py", line 228, in adapt
>     set(output.keys()) == output_keys[i]
> AssertionError: Adapted output keys do not match with the original output keys

**Expected behavior**

**Additional context**

**Comment by shahules786** [comment]
Hey @vadimbezborodow can you try with gpt-4?
