### ISSUE TITLE
AttributeError: 'ChatVertexAI' object has no attribute 'set_run_config'

### ISSUE THREAD

**Issue by tagboola** [explodinggradients/ragas#829]
[x] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
I tried following https://docs.ragas.io/en/stable/howtos/customisations/gcp-vertexai.html to run RAGAS with Vertex AI but it's failing with `AttributeError: 'ChatVertexAI' object has no attribute 'set_run_config'`.

Ragas version: `0.1.5`
Python version: `3.9.13`
`langchain-google-vertexai` version: `0.1.2`

**Code to Reproduce**
Share code to reproduce the issue

```
creds, _ = google.auth.default(quota_project_id=project_id)
ragas_vertexai_llm = ChatVertexAI(credentials=creds)

metrics = [
    context_precision,
    faithfulness,
    answer_relevancy,
]

for m in metrics:
m.__setattr__("llm", ragas_vertexai_llm)

# evaluate the dataset
result = evaluate(
	  eval_data,
	  metrics = metrics
)
```

**Error trace**
```
Traceback (most recent call last):
  File "<path-to-script>/test.py", line 37, in <module>
    result = evaluate(
  File "<path-to-pyenv>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ragas/evaluation.py", line 179, in evaluate
    [m.init(run_config) for m in metrics]
  File "<path-to-pyenv>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ragas/evaluation.py", line 179, in <listcomp>
    [m.init(run_config) for m in metrics]
  File "<path-to-pyenv>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ragas/metrics/base.py", line 118, in init
    self.llm.set_run_config(run_config)
AttributeError: 'ChatVertexAI' object has no attribute 'set_run_config'
```

**Expected behavior**

I expected the evaluation to succeed.

**Additional context**

**Comment by Adi8885** [comment]
@tagboola Please try to wrap the "ChatVertexAI" class . Below code

```
from ragas.llms.base import LangchainLLMWrapper

creds, _ = google.auth.default(quota_project_id=project_id)

#TODO : Wrap the ChatVertexAI as below
llm = ChatVertexAI(credentials=creds)
ragas_vertexai_llm = wrapper = LangchainLLMWrapper(llm)

metrics = [
    context_precision,
    faithfulness,
    answer_relevancy,
]

for m in metrics:
m.__setattr__("llm", ragas_vertexai_llm)

# evaluate the dataset
result = evaluate(
	  eval_data,
	  metrics = metrics
)
```

Hope this helps

**Comment by tagboola** [comment]
I actually got this working by setting the `llm` parameter of the `evaluate` method. 

```
```
