### ISSUE TITLE
Metrics answer_similarity and answer_correctness not working with VertexAIEmbeddings

### ISSUE THREAD

**Issue by deveshch** [explodinggradients/ragas#876]
**Describe the bug**
The issue appears when using any of the above mentioned metrics with VertexAIEmbeddings. The langchain.embeddings VertexAIEmbeddings does not implement embed_text and RAGAS code attempts to call to the embedding model in the stated way.

Ragas version: 0.1.7
Python version: 3.10.12

**Code to Reproduce**
```
from langchain.chat_models import ChatVertexAI
from langchain.embeddings import VertexAIEmbeddings
from ragas.llms.base import LangchainLLMWrapper
from ragas import evaluate

from ragas.metrics import (
    answer_similarity,
    answer_correctness,
)

metrics = [
    answer_similarity,
    answer_correctness,
]

ragas_vertexai_llm = ChatVertexAI(credentials=creds)

llm_wrapper = LangchainLLMWrapper(ragas_vertexai_llm)

vertexai_embeddings = VertexAIEmbeddings(credentials=creds)

for m in metrics:
    m.__setattr__("llm", llm_wrapper)
    if hasattr(m, "embeddings"):
        m.__setattr__("embeddings", vertexai_embeddings)

result = evaluate(
    evaluation_dataset,
    metrics=metrics,
    llm=llm_wrapper,
    embeddings=vertexai_embeddings
)
```

**Error trace**

Runner in Executor raised an exception
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/site-packages/ragas/executor.py", line 79, in _aresults
    r = await future
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/site-packages/ragas/executor.py", line 38, in sema_coro
    return await coro
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/site-packages/ragas/executor.py", line 112, in wrapped_callable_async
    return counter, await callable(*args, **kwargs)
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/site-packages/ragas/metrics/base.py", line 116, in ascore
    raise e
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/site-packages/ragas/metrics/base.py", line 112, in ascore
    score = await self._ascore(row=row, callbacks=group_cm, is_async=is_async)
  File "/Users/xxx/miniconda3/envs/env_3.10.12/lib/python3.10/site-packages/ragas/metrics/_answer_similarity.py", line 65, in _ascore
    embedding_1 = np.array(await self.embeddings.embed_text(ground_truth))
AttributeError: 'VertexAIEmbeddings' object has no attribute 'embed_text'

**Comment by deveshch** [comment]
I was able to fix the issue as follows:

```
from ragas.embeddings import LangchainEmbeddingsWrapper
vertexai_embeddings = LangchainEmbeddingsWrapper(VertexAIEmbeddings(credentials=creds))
```

**Comment by deveshch** [comment]
I was able to fix the issue as follows:

```
from ragas.embeddings import LangchainEmbeddingsWrapper
vertexai_embeddings = LangchainEmbeddingsWrapper(VertexAIEmbeddings(credentials=creds))
```
